# frozen_string_literal: true

source 'https://rubygems.org'

gem 'faraday'
gem 'json'


group :test do
  gem 'faastruby'
  gem 'faastruby-rpc'
  gem 'rspec'
  gem 'webmock'
  gem 'vcr'
end

group :development, :test do
  gem 'pry-byebug'
end
